[build]
  command = "npm install"
  publish = "."
  functions = "functions"

[functions]
  external_node_modules = ["puppeteer-core", "puppeteer"]
  included_files = ["*.pptx", "*.html"]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[build.environment]
  AWS_LAMBDA_JS_RUNTIME = "nodejs18.x" 